In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def BCSE_AI_ML_5B():
    a=10
    b=20
    c=a+b
    print("Hello Class the Sum is :=",c)
    pass
    
def Sub():
    x=12
    y=20
    x=x-y
    print(x)    
    pass
    
    
def main():
    BCSE_AI_ML_5B()
    Sub()
    
main()


Hello Class the Sum is := 30
-8


In [3]:
import numpy as np

BCSE_AI_ML_5B = np.array([[1,20,31,4,15], [16,72,18,9,10]])

print('2nd element on 1st row: ', BCSE_AI_ML_5B[1, 2])

2nd element on 1st row:  18


In [4]:
for i in range(0,len(BCSE_AI_ML_5B)):
    print(BCSE_AI_ML_5B[i])
    print("\n")

    print('Shape :',BCSE_AI_ML_5B.shape)
    print('Rows = ',BCSE_AI_ML_5B.shape[0])
    print('Columns = ',BCSE_AI_ML_5B.shape[1])

[ 1 20 31  4 15]


Shape : (2, 5)
Rows =  2
Columns =  5
[16 72 18  9 10]


Shape : (2, 5)
Rows =  2
Columns =  5


In [5]:
np.zeros(3)


array([0., 0., 0.])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1])

In [8]:
np.random.rand(2,3)

array([[0.13944508, 0.67920168, 0.72277744],
       [0.41969641, 0.24826178, 0.9472425 ]])

In [9]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [10]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
#reshape
BCSE_AI_ML_5B = np.array([3,6,9,12,2,2])
np.reshape(BCSE_AI_ML_5B,(3,2))

array([[ 3,  6],
       [ 9, 12],
       [ 2,  2]])

In [12]:
# While reshaping, if you are unsure about the shape of any of the axis, just input -1. 
#NumPy automatically calculates the shape when it sees a -1:
BCSE_AI_ML_5B= np.array([32,16,9,12,118,24,21,0,0])
print('Three rows :','\n',np.reshape(BCSE_AI_ML_5B,(3,-1)))
print('Three columns :','\n',np.reshape(BCSE_AI_ML_5B,(-1,3)))


Three rows : 
 [[ 32  16   9]
 [ 12 118  24]
 [ 21   0   0]]
Three columns : 
 [[ 32  16   9]
 [ 12 118  24]
 [ 21   0   0]]


In [13]:
BCSE_AI_ML_5B = np.array([1, 2, 3, 4])

#print(BCSE_AI_ML_5B[3])
for i in BCSE_AI_ML_5B:
    print(BCSE_AI_ML_5B[i-1])
    print("\n")

1


2


3


4




In [14]:
BCSE_AI_ML_5B = np.array([1, 2, 3, 4])

#print(BCSE_AI_ML_5B[0])

for i in range(0,len(BCSE_AI_ML_5B)):
    print(BCSE_AI_ML_5B[i-1])
    print("\n")

4


1


2


3




In [15]:
BCSE_AI_ML_5B = np.array([[10, 12, 30], [14, 51, 16]])

for i in BCSE_AI_ML_5B:
  for j in i:
    print(j)

10
12
30
14
51
16


In [16]:
import numpy as np

BCSE_AI_ML_5B = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in BCSE_AI_ML_5B:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [17]:
BCSE_AI_ML_5B = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(BCSE_AI_ML_5B):
  print(x)

1
2
3
4
5
6
7
8


In [18]:
#Sometimes when you have a multidimensional array and want to collapse it to a single-dimensional array, 
#you can either use the flatten() method or the ravel() method:

BCSE_AI_ML_5B = np.ones((3,3))
b = BCSE_AI_ML_5B.flatten()
c = BCSE_AI_ML_5B.ravel()
print('Original shape :', BCSE_AI_ML_5B.shape)
print('Array :','\n', BCSE_AI_ML_5B)
print('Shape after flatten :',b.shape)
print('Array :','\n', b)
print('Shape after ravel :',c.shape)
print('Array :','\n', c)

#But an important difference between flatten() and ravel() is that the former returns a copy of the original array
#while the latter returns a reference to the original array

Original shape : (3, 3)
Array : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Shape after flatten : (9,)
Array : 
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
Shape after ravel : (9,)
Array : 
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [19]:
#SLicing
BCSE_AI_ML_5B = np.array([11, 20, 13, 4, 15, 60,17])
print(BCSE_AI_ML_5B[1:5])
print(BCSE_AI_ML_5B[1:])
print(BCSE_AI_ML_5B[:5])
print(BCSE_AI_ML_5B[:])
print(BCSE_AI_ML_5B[0:5:2])
print(BCSE_AI_ML_5B[::1])
print(BCSE_AI_ML_5B[:5:2])
print(BCSE_AI_ML_5B[-1:-5])
print(BCSE_AI_ML_5B[-5:-1])


[20 13  4 15]
[20 13  4 15 60 17]
[11 20 13  4 15]
[11 20 13  4 15 60 17]
[11 13 15]
[11 20 13  4 15 60 17]
[11 13 15]
[]
[13  4 15 60]


In [20]:
#Sorting 
BCSE_AI_ML_5B = np.array([3, 2, 0,29,1,10,23,86,23,22])
print(np.sort(BCSE_AI_ML_5B))

BCSE_AI_ML_5B = np.array(['Soumen','Avik','Kanpur'])
print(np.sort(BCSE_AI_ML_5B))

BCSE_AI_ML_5B = np.array([[[10, 2], [30, 4]], [[25, 6], [27, 8]]])
print(np.sort(BCSE_AI_ML_5B))

[ 0  1  2  3 10 22 23 23 29 86]
['Avik' 'Kanpur' 'Soumen']
[[[ 2 10]
  [ 4 30]]

 [[ 6 25]
  [ 8 27]]]
